### ISSUE TITLE
How to get this app on Android?

### ISSUE THREAD

**Issue by GoluLiliput** [uwaisalqadri/MangaKu#1]
Hello how can I run this app on Android. Can I have some sort of apk please???
The app looks really really awesome!!

**Comment by ghost** [comment]
hi, i really apreciate it, but unfortunately the actual app is kinda like a “lite version” of the design because i have not yet found a good public api for free manga reader

i’ll give you the current apk soon, thanks!

**Comment by GoluLiliput** [comment]
Please please give it to me asap🥺🥺🥺

**Comment by uwaisalqadri** [comment]
i'm so sorry it takes me so long, hope u still there :)

https://drive.google.com/file/d/14aQU6fXm4_KmF4PxOysy5IzPvbvfWj_F/view?usp=sharing

**Comment by GoluLiliput** [comment]
I m so happy that u did respond. I had really thought u would have forgotten. Thank u so much bringing me the app in its debug state. Right now I can't read manga on the app right? Are u going to implement that?

**Comment by uwaisalqadri** [comment]
yes I am, I'm just currently not found any **public API** that would support this app for manga reading, contact me if you find any
