### ISSUE TITLE
[Bug]: Realm.close wasn't called 

### ISSUE THREAD

**Issue by mahmed1987** [uwaisalqadri/MangaKu#4]
### Contact Details

m.ahmed.abutalib@gmail.com

### What happened?

When are we supposed to call realm.close ? I was trying to take some inspiration for that in this project but i can't see it called anywhere here too . 

Isn't it essential to call realm.close ?

https://www.mongodb.com/docs/realm/sdk/java/realm-files/open-and-close-a-realm/#std-label-java-close-a-realm

### Version

Latest Version

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by uwaisalqadri** [comment]
I'm not aware of it since the update to kotlin 2, let me check the docs, thank you for raising the issue 👍

**Comment by uwaisalqadri** [comment]
fixed at [#edbf625](https://github.com/uwaisalqadri/MangaKu/commit/edbf625688917d1362703791833b2bc63a9dae5c), thank you @mahmed1987
